---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 2: Introduction to Alternative Investments

## SubTopic 2.3: Accessing Alternative Investments

### Types of Alternative Investment Funds

The universe is generally split between fund structures commonly used for investment strategies in which the underlying investments are either public (i.e., liquid) securities or private (i.e., illiquid) securities.

The bulk of strategies focused on investing in public/liquid securities exist within the hedge fund universe. 

Hedge funds employ the fund structure known as open-end funds, or evergreen funds.

There are several elements common to all open-end funds:

i) New capital may be invested into the fund throughout the operation of the fund.

ii) The fund issues new shares when capital is added to the fund. Thus per share value of the fund is unaffected by inflows into the fund.

iii) Capital may be redeemed from the fund throughout the operation of the fund.

iv) Fund redemptions are filled on a per share basis. Thus per share value of the fund is unaffected by outflows from the fund.

v) At launch, the fund has an indefinite life span.

vi) The fund charges an asset-based fee as a percentage of assets under management.

vii) The fund charges an incentive-based fee based on fund performance over a specified period as opposed to overall performance at the time of redemption.

viii) If the value of the fund decline following calculation of an incentive fee, the existing investors in the fund will not be charged an incentive fee again until the fund value rises above the level when the last incentive fee was charged (i.e. high-water mark).
This level ensures that incentive fees are not charged twice for the same performance outcome.






