---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 2: Introduction to Alternative Investments

## SubTopic 2.4: Quantitative Foundations

### Return and Rate Mathematics

- The Compounding Assumption

Compounding is the recognition of reinvestment of capital, such as interest on interest or, earnings on earnings.

Simple interest is an interest rate computation approach that does not incorporate compounding.

The vast majority of investment reporting and analysis is based on the assumption of compounding.

Returns of short intervals would be adjusted to reflect the compound performance over a full year.

Continuous compounding assumes that earnings can be instantaneously re‐invested to generate additional earnings. 

Discrete compounding includes any compounding interval other than continuous compounding such as daily, monthly, or annual.

- Discrete Compounding














































