---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 2: Introduction to Alternative Investments

## SubTopic 2.9: Alpha, Beta, and Hypothesis Testing

### Overview of Beta and Alpha

Alpha describes skill-based return performance; and beta indicates market-based return performance. 

These are challenging to measure in alternative investments.

- Beta

In CAPM (capital asset pricing model), the concept of beta is identified: Each asset has one beta, and the beta is specified as the covariance of the asset's return with the return of the market portfolio, divided by the variance of the returns of the market portfolio. 

This is also the definition for a regression coefficient in a simple linear regression of an asset's returns on the returns of the market portfolio.

Beta is the proportion by which an asset's return less the risk free rate moves in response to the market portfolio's return less the risk free rate. 

But beta has a more general interpretation outside CAPM, both within traditional investment analysis and alternative investment analysis.

Beta refers to a measure of risk, or the bearing of risk, wherein the underlying risk is systematic and is rewarded with expected return.

Outside CAPM model, assets can have more than one beta, and a beta does not have to be a measure of the response of an asset to fluctuations in entire market portfolio.

Bearing beta risk is viewed as a source of higher expected return. 

Understanding the exposure and level of systematic risk is essential in evaluating the returns of a manager.

An investor may assume a market-neutral hedge fund manager has no beta, and the entirety of the return is explained by alpha.

However, additional analysis may reveal the manager had underlying market exposure that contributed to performance. 

Some fee structures may be structured to incentivize maximum alpha generation. 

Investors will pay high fees for alpha, however, realizing much of those fees are being paid to reward beta may not feel as appropriate. 

- Alpha

Conveys the realization of superior risk‐adjusted performance, while not universally agreed upon, many investors would suggest an implication of superior risk-adjusted performance via skill.

Early quantitative measurements of alpha stated Alpha refers to any excess or deficient investment return after the return has been adjusted for the time value of money (risk‐free rate) and for the effects of bearing systematic risk (beta). 

As investors have become more sophisticated in measuring and disaggregating returns, there is a greater recognition that other non-skill-based factors beyond systematic factors may contribute to returns (e.g. illiquidity premium, style-based factors, etc.). 

The challenge for investors is quantitative tools used to measure alpha may not always perfectly align with common qualitative reference of alpha. 

The extent to which the skill, information, and knowledge of an investment manager generate superior risk‐adjusted returns, when adjusting for all relevant/measurable risk factors (or inferior risk‐adjusted returns in the case of negative alpha).

\newpage

### Return Drivers

Return drivers represent the investments, the investment products, the investment strategies, or the underlying factors that generate the risk and return of a portfolio.

A simplified way to manage a total portfolio is to divide its assets into two groups: beta drivers and alpha drivers. 

In the context of a portfolio, an investment whose returns are most sensitive to moves in the overall market or a particular risk factor is a beta driver.

An investment whose primary sources of returns are independent of the market is an alpha driver.

- Beta Drivers

Beta drivers capture market risk premiums, and good/pure beta drivers do so in an efficient (i.e. precise and cost‐effective) manner.

Beta drivers capture risk premiums by bearing systematic risk.

Bearing beta risk as defined by CAPM has been extremely lucrative over the long run. 

The long‐term tendency of beta drivers to earn higher returns from equity investments than are earned on risk‐free investments is attributed to the equity risk premium.

The equity risk premium puzzle is the enigma that equities have historically performed much better than can be explained purely by risk aversion, yet many investors continue to invest heavily in low‐risk assets. 

- Alpha Drivers

Alpha drivers seek excess return or added value through generating returns that exceed the returns on investments of comparable risk.

Many alternative assets present opportunities for skillful managers to benefit from and capture alpha drivers. 

They seek sources of return less correlated with traditional asset classes, which reduces risk in the entire portfolio in the process. 

The analysis of the ability of a manager to capture alpha drivers are the focus of much of alternative investing. 

Alternative investments are often touted as being able to generate greater combinations of return and risk by providing return streams that have relatively low correlation with traditional stock and bond markets but comparable average returns.

- Passive Beta Drivers as Pure Plays on Beta

Passive investing, such as employing a buy‐and‐hold strategy to match a benchmark index, is a pure play on beta: simple, low cost, and with a linear risk exposure. 

A linear risk exposure is when returns to such a strategy are graphed against the returns of the market index or another appropriate standard, the outcomes tend to lie on a straight line. 

Options and investment strategies with shifting betas have non-linear risk exposures.

A passive beta driver strategy generates returns that follow the up‐and‐down movement of the market on a one‐to‐one basis.

Pure beta drivers are linear in their performance compared to a financial index.

- Product Innovators and Process Drivers

Much of alternative asset management industry has added strategies in the tails of alpha driver–beta driver spectrum.

At one end of the spectrum are product innovators, which are alpha drivers that seek new investment strategies devoid of beta drivers offering superior rates of risk‐adjusted return.

At the other end are alternative investment replication strategies, which offer beta and other factor exposures as efficiently as possible without any pretense of skill-based alpha seeking.

This end of the spectrum has similarly experienced great innovation and development of beta driven process drivers. 

Process drivers are beta drivers that focus on providing beta and/or factor exposures that are fine‐tuned or differentiated.

These process drivers may try to identify the traditional risk factors with the greatest correlation to the strategy and create a lower cost diversified portfolio for investors desiring these targeted risk exposures.

The increased difficulty for a fund manager to capture alpha or to compete with the extremely low‐cost asset gatherers has put pressure on beta drivers with high fees.

\newpage

### Challenges in Estimating Alpha

A key difference between expected (forecasted) and realized alpha is that forecasted alpha reflects skill, whereas realized alpha is a combination of both luck and skill. 

A key method of identifying alpha for a particular investment fund includes a thorough and rigorous qualitative analysis of the manager and the manager's processes and methods.

Empirical methods estimate alpha through attempting to differentiate between the roles of luck and skill in generating past risk‐adjusted returns. 

The objective of these empirical analyses is to understand how much, if any, of an investment's past returns are attributable to skill and might be predicted to recur.

- Two Steps to Empirical Analysis of Ex Ante Alpha

1) Asset pricing model or benchmark is used to divide historical returns into portions attributable to systematic risk factors (and risk‐free rate) and those attributable to idiosyncratic effects (i.e. skill/alpha).

2) Remaining returns (idiosyncratic returns) should be statistically analyzed to estimate the extent to which the superior returns may be attributable to skill rather than luck.

Alpha estimation is the process of adjusting realized returns for risk and the time value of money. 

If historical risk‐adjusted returns are very consistently positive or negative, the analyst is increasingly confident that the underlying investment offered a positive or negative alpha.

- Alpha Estimation and Return Persistence

Model misspecification is any error in the identification of the variables in a model or any error in identification of the relationships between the variables.

Model misspecification inserts errors in the interpretation and estimation of relations.

Inefficiencies exist and abnormally good and bad performances have been predictable based on past data in many instances.

There are also many instances in which investors have incorrectly used past performance to indicate future results.

Abnormal return persistence is the tendency of idiosyncratic performance in one time period to be correlated with idiosyncratic performance in a subsequent time period. 

- Separating Luck and Skill with Return Persistence

Assume a reasonably accurate performance attribution has distinguished returns due to systematic risks from those due to idiosyncratic risks. 

The next step is to attribute the idiosyncratic returns to their sources: luck, skill, or both.

Proper attribution of idiosyncratic returns (alpha) to luck or skill is a statistical challenge.

Attempting to identify alpha through an abnormal return persistence procedure is summarized in the steps:

  i) Estimate average idiosyncratic returns (alpha) for each asset in time period 1
  
  ii) Estimate average idiosyncratic returns (alpha) for each asset in time period 2.
  
  iii) Statistically test whether alphas in time period 2 are correlated with alphas in time period 1.

- Interpreting Estimated Return Persistence

A statistically significant positive correlation between average idiosyncratic returns in consecutive periods implies positive return persistence. 

To extent that return model has been correctly specified, consistent and statistically significant positive correlation would lead to increased confidence that managerial skill has driven some or all of investment results.

This approach differs markedly from the more common approach of using a single time period to identify top returns and assuming that top returns were driven by skill.

However, just because an investment experiences positive return persistence in two consecutive periods does not prove the returns are based on skill. 

Quantitative measurements help evaluate whether historical returns exhibited (persistent) alpha, however analyst needs to apply a qualitative overlay as well.

\newpage

### Return Attribution, Alpha, and Beta

#### Example 1

Assume Fund A trades unlisted securities that are not efficiently priced, has a beta of 0.75, and has an expected return of 9%.
The expected return of the market is 10% and the risk‐free rate is 2%. 
During the next year, the market earns 18% and Fund A earns 17%.

1) What was the fund's forecasted alpha?

2) What was the fund's realized alpha?

3) What was the amount of realized alpha that was luck?

4) What was the amount of the realized alpha that was skill?

=>

1) Forecasted alpha is found as intercept of ex ante version of single‐factor market model (CAPM‐style model).
$$\mathbb{E}[R_A] = R_f + \beta_A (\mathbb{E}[R_m] - R_f)$$

$$= 2\% + 0.75(10\%-2\%) = 8\%$$
Thus
$$\text{Alpha} = \text{Expected Return} - \text{Required Return}$$
$$= 9\% - 8\% = 1\%$$
Thus, Fund A offers 1% more return than required based on its systematic risk (i.e. forecasted alpha of 1%).

2) Realized alpha is found from ex post version of the single‐factor market model
$$\mathbb{E}[R_A] = R_f + \beta_A (\mathbb{E}[R_m] - R_f) + \epsilon$$
$$\text{Alpha} (\epsilon) = 17\% -  2\% - 0.75(18\%-2\%) = 3\%$$

Even though Fund A underperformed the market portfolio prior to risk adjustment, it performed 3% better than assets of similar risk.

3) & 4) Since the analysis assumes the fund offers an expected superior return, or forecasted alpha, of 1%, then 1% (i.e. one‐third) realized alpha of 3% is said to be attributable to skill and 2% (i.e. two thirds of 3%) attributable to good luck (positive idiosyncratic return).

- Three Types of Model Misspecification

Errors in estimating alpha can result from model misspecification, including misspecification of a benchmark. 

With any factor market model, alpha is the error term, or the unexplained return (the return left over after attributing return to the designated factors).

This does not mean unexplained return is pure skill, it could likely be return attributable to beta/factors not present in the model. 

Three primary types of model misspecification can confound empirical return attribution analyses:

  i) Omitted (or misidentified) systematic return factors is the failure to include relevant factors in an analysis of returns such as momentum or size.
  
  ii) Misestimated betas is estimation error due to randomness or econometric errors such as failure to correct for heteroskedasticity.
  
  iii) Non-linear risk‐return relation error is the failure to model non-linearity such as quadratic or cubic effects.

Because systematic risks have a positive expected return, omitting a significant risk factor or underestimating a beta tends to overstate the manager's skill by attributing beta return to alpha.

- Beta Nonstationarity

Beta nonstationarity is one reason why return can be attributed to systematic risk with error. 

Beta non-stationarity is a general term referring to tendency of systematic risk of a security, strategy, or fund to shift through time.

That is, a return series containing leverage is expected to have a changing systematic risk through time if leverage changes through time. 

A type of beta non-stationarity observed in hedge funds is beta creep. 

Beta creep is when hedge fund strategies pick up more systematic market risk over time.

When assets pour into hedge funds, it's expected that the managers of the funds will allow more beta exposure in their portfolios in an attempt to maintain expected returns in an increasingly competitive and crowded financial market. 

This causes the creeping effect: over time, as the alphas of available investment opportunities decline, the amount of systematic risk in portfolios will creep upward.

The betas of funds may also be non-stationary because of market conditions rather than changes in the fund's underlying assets. 

In periods of economic stress, the systematic risks of funds increase.

Beta expansion is the perceived tendency of the systematic risk exposures of a fund or asset to increase due to changes in general economic conditions. 

Beta expansion is observed in down market cycles and is attributed to increased correlation between the hedge fund's returns and market returns.

Another example of beta non-stationarity is market timing, the intentional shifting of an investment's systematic risk exposure by its manager. 

The fund manager takes on a positive beta exposure when their analysis indicates the market is likely to rise and takes on a negative beta, or a short position, when they perceive the market is likely to decline. 

This beta non-stationarity (or beta shifting) makes return attribution more problematic, since the level of beta between reporting periods would be very difficult to estimate accurately.

\newpage

### Statistical Issues in Analyzing Alpha and Beta

- Non‐Normality and the Cross‐Sectional Search for Alpha

Cross‐sectional searches for alpha are prone to error when performance is analyzed with methods that assume normally distributed returns.

Cross‐sectional return differentials exist, but dispersion alone does not mean that skill is involved. 

The existence of any thickness or length to the tails of a frequency distribution of fund returns provides little or no evidence that dispersion is caused by skill rather than luck.

- Outliers and the Search for Alpha

Another area of concern is whether empirical findings are being driven by one or more outliers.

An outlier is an observation that is markedly further from the mean than almost all other observations. 

Outliers tend to have large impacts on results, and an exceptionally unusual outlier may severely distort the measurement of the economic tendencies of the data in traditional tests, especially in the case of small samples. 

Many statistical methodologies use squared values. 
When an outlier value is squared, its impact on the analysis can be huge. 

However, outliers also represent behavior that can be reasonably expected to recur, and therefore their inclusion in a sample may be useful in generating results that predict behavior well. 

Outliers result from non‐normally distributed variables, and they are detected through visual inspection of plots or listings of observations ranked by the size of the regression residuals.

If past results are attributable to an outlier, an analysis based on those results provide a poor indication of the future unless it is clear that the outlier is as likely to occur in the future as it was likely to occur in the past.

- Biased Testing and the Search for Alpha

Two issues of biased testing are:

  i) Was the fund being analyzed selected at random, or was the fund identified prior to the sample period being analyzed?
  
  ii) Were the test procedures fully specified prior to the analysis of any results?

The first issue speaks to tendency to observe a fund that performed well and test if performance is statistically superior.

The second issue speaks to specification of test and importance of avoiding data dredging. 

Each statistical test involves numerous decisions, such as: 

  1) specification of return model and benchmark or peer group, 
  2) specification of sample period, and 
  
  3) specification of significance level.
  
It's vital these decisions are made prior to conduct of test to avoid varying the specifications in search of a more favorable result.

- Spurious Correlation, Causality, and Beta Estimation

Beta estimation is a crucial task in measuring systematic risk for use in risk adjustment of returns. 

As a measure of correlation rather than a measure of central tendency, beta is inherently more difficult to analyze and more subject to complexities. 

Further, estimates of betas and correlations based on historical data can be highly unreliable. 

The difference between spurious correlation and true correlation is that spurious correlation is idiosyncratic in nature, coincidental, and limited to a specific set of observations. 

Estimates of security betas, even using a single‐factor market model, are remarkably unstable over different time periods. 

The estimated beta of individual stocks is regarded as so erratic that published estimates of beta are automatically adjusted for their historical tendencies toward 1.0 when used to predict future betas. 

The estimated correlation is being driven both by true correlation and by spurious correlation.

The difference between true correlation and causality is that causality reflects when one variable's correlation with another variable is determined by or due to the value or change in value of the other variable. 

When the overall economy performs very well, it causes the net asset value of a long‐only equity fund to rise.

When economic reasoning indicates a causal relationship between two variables, an analyst or a researcher can be more confident that an observed correlation is true rather than spurious.

- Fallacies of Alpha and Beta Estimation

Alpha estimation is central to detecting enhanced returns, while beta estimation is central to measuring non-diversifiable risks of investments. 

- Three Fallacies of Alpha Estimation

NB: These are correct versions, not fallacies!

1) Fallacy 1: Returns should be analyzed using a risk‐adjusted standard, such as a benchmark or an asset pricing model of efficiently priced assets, rather than compared to each other, and the results should be visually examined.

2) Fallacy 2: A hypothesis test is based on critical assumptions, so a test using a particular asset pricing model is only as reliable as the model itself.

3) Fallacy 3: The level of significance used in a hypothesis test is not the probability that the null hypothesis is false if a statistically significant result is found. 
With a well‐specified model, a fund that has zero alpha has only a 1% chance of being incorrectly estimated as having a nonzero alpha.

- Two Fallacies of Beta Estimation

Beta estimation fallacies include the third fallacy of alpha estimation: that a statistically significant result with a significance level of 10% indicates that null hypothesis has a 90% chance of being false.

1) Fallacy 1: Traditional correlation measures indicate a linear response between the variables but may not capture some nonlinear relationships, such as U‐shaped or V‐shaped relationships.

2) Fallacy 2: Correlation can be different from causation.
Economic intuition should play a role alongside empirical techniques to avoid misinterpretation of spurious correlation and to lessen the possibility of data dredging.















