---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 3: Real Assets

## SubTopic 3.2: Commodities

### Investing in Commodities without Futures

Other popular methods of obtaining exposure to commodity returns: direct physical commodity ownership, equity‐related commodity investments, exchange‐traded funds (or notes), and commodity‐linked notes.

- Three Disadvantages of Direct Investment in Physical Commodities

Institutional investors obtain exposure to commodities through derivative contracts rather than through physical inventories for several reasons: 

  1) to avoid storage costs and other disadvantages of moving, maintaining, and managing inventories; 
  
  2) to avoid wasting the convenience yield implicit in physical inventories; and 
  
  3) to avoid the opportunity cost of capital or financing costs of purchasing physical inventories. 

- Hotelling's Theory and Attractive Direct Commodity Returns

The two hypotheses propose distinct views on direct commodity investments: 

  1) expected long‐run returns of direct commodity investment are attractive, or
  
  2) they are unattractive.

Hotelling's theory states that prices of exhaustible commodities should increase by prevailing nominal interest rate, perhaps with a risk premium.

Ignoring storage costs, expected spot prices of commodity i at a horizon point of T years, $\mathbb{E}[P_{i,T}]$, should be equal to the future value of the current spot price compounded at the nominal riskless rate plus a risk premium 
$$\mathbb{E}[P_{i,T}] = P_{i,0}e^{rT}$$
where $r$ - risk‐adjusted continuously compounded return required for holding commodity i for T years. 

In theory, it's conceivable that $r$ for a particular commodity could be less than default‐free nominal interest rate if there were inflation risk‐reducing or systematic risk‐reducing attributes of the particular commodity that were perceived by the marginal investor to be so attractive as to justify investment with a negative risk premium.

Generally, the spot commodity prices are expected grow at a rate equal to an appropriately risk‐adjusted nominal rate.

- Simon and Unattractive Direct Commodity Returns

Long‐run expected spot prices of commodities (in real or inflation‐adjusted terms) can be consistently less than predicted by Hotelling's theory
$$\mathbb{E}[P_{i,T}] \le P_{i,0}e^{rT}$$
The above views Hotelling's theory as ignoring technological changes.

It uses an inequality to set only an upper bound on expected spot prices. 

If the current price, $P_{i,T}$, is such that the left side exceeds the right side, arbitrageurs could purchase commodities and hold them, with the expectation of selling them at time T at a price that offers a superior expected return.

However, restrictions and frictions on short‐selling do not allow arbitrage in the other direction. 

Models that allow technological innovation predict that commodities can have expected spot prices that are lower than those predicted by Hotelling's theory, making direct investment in physical inventories unattractive in the absence of benefits derived from convenience yield.

- The Idiosyncratic Risks and Two Betas of Commodity‐Related Equities

Another way to gain exposure to commodities is owning securities of firms that derive substantial part of revenues from sale of physical commodities.

A problem is that most firms have revenues related to a variety of commodities or have operations that extend outside activities directly related to ownership and extraction of commodities.

As a result, share price of most firms will be poorly correlated with price of single commodity.

There are reasons why a firm focused on a single commodity might not be a good proxy for direct investment in firm's underlying commodity:

  i) high correlation between stock price and commodity price assumes firm has not hedged its exposure to commodity through short positions in forward or futures contracts. 
  
  ii) firm must own underlying commodities (or rights) rather than purchasing commodities or leasing rights at market prices.

Although earnings per share (EPS) of commodity‐producing firm may be somewhat highly correlated to the price of the underlying commodity, price‐to‐earnings (P/E) ratio may not be.

If stock market declines quickly, P/E ratios tend to fall throughout various sectors. 

When commodity prices and inflation are increasing, the decline in overall market P/E ratios could lead to decline in P/E ratio and prices of commodity‐producing firms.


