---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 3: Real Assets

## SubTopic 3.3: Other Real Assets

###  Commodity Producers

Investments in natural resources attract investor interest based on their perceived ability to serve as diversifiers against general economic fluctuations and the risk of unexpected inflation.

- Natural Resource Prices as a Driver of Operating Firm Performance

A key issue is extent to which investments in firms that process natural resources provide similar risk and return characteristics to direct investments in underlying natural resources. 

The correlations between returns of firms and price changes for their associated goods are driven by 3 primary factors: 

  i) price elasticity of demand for the good, 
  
  ii) price elasticity of supply of the good, and
  
  iii) extent to which an operating firm is exposed to or has hedged changes in its profits.

Accordingly, absent hedging strategies, large price increases in commodity should drive anticipation of higher profits in firms that provide goods and services in production of that commodity.

- Evidence on Commodity Prices and the Equity Prices of Operating Firms

Empirical evidence also provide insight into relationship between commodity prices and equity prices of operating firms.

Share prices of firms related to a commodity depend partially on value of the commodity. 

If firms are publicly traded, their performance is substantially correlated with overall performance of public equity markets.

- Commodity Prices and Operating‐Firm Equity Return Correlations

Rather than the returns of firms being driven entirely by the contemporaneous prices of related commodities, they are also driven by market's anticipation of dynamic supply and demand factors more related to the long‐term profitability of the goods and services directly offered by those firms, which in turn tend to be correlated with overall equity markets.

To the extent that the returns of firms within the ETFs are driven by operational issues, the investments will serve more as traditional equity investments rather than as diversifiers or any other type of alternative investment vehicle.

\newpage

### MLPs – a Real Assets Liquid Alternative









































































