---
author: |
  - |
    Mbanguta Lwando
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
classoption: notitlepage
geometry: margin=1in
header-includes:
  - "\\usepackage{graphicx}"
  - \usepackage{pdfpages}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic 3: Real Assets

## SubTopic 3.6: Real Estate Methods

### Real Estate Development

- How to Analyze a Development Investment

Real estate investing involves making decisions with incomplete information. 

The assumptions that go into the analysis of a real estate investment are critical. 

Sophisticated software models make the work of analyzing potential investments more efficient by performing calculations quickly and allowing for “what-if” scenarios, but the outcomes are only as good as the assumptions used as inputs.

Researching and evaluating the assumptions is the hallmark of a good analyst.

A simple but effective way for an investor to evaluate the viability of a development project is to calculate the development yield: the expected unlevered stabilized return on the cost of development.

The calculation involves dividing the expected stabilized annual net operating income (NOI) by the expected total development costs:
$$\text{Development yield} = \frac{\text{Stabilized annual NOI}}{\text{Total development costs}}$$

Developing the estimate for the expected stabilized NOI requires the analyst to perform market due diligence to project revenue and expenses. 

This research is critical for making the development yield a useful investment tool.

Development costs are classified as either hard costs or soft costs. 

Hard costs as physical goods, whereas soft costs are services necessary to develop the project.

Estimating NOI is more challenging than estimating development costs.

Construction costs are established through a bid process. 

Expected rental income must be estimated from the analyst’s research of rental rates and occupancies of existing competitive properties. 

The analyst should investigate the number of additional developments that have been permitted in order to estimate the potential effect on the local market of this additional rental space. 

The analyst must also explore future demand by researching those factors that are driving changes in the population and employment growth rates.

Property operating costs must also be researched to formulate an estimate of stabilized NOI.

The investor can estimate the gross expected sales price of the development and the development profit by dividing the projected stabilized NOI by the market cap rate:
$$\text{Expected sales price} = \frac{\text{Projected stabilized NOI}}{\text{Cap rate}}$$

The lower the market cap rate is relative to the development yield, the more profitable it'll be to develop. 

This is a positive development spread.

The larger this positive spread is, the more likely it is for other investors to undertake development projects.

Conversely, the investor would not move forward with the project if the market cap rate was higher than the development yield. 

In the latter case, market rents do not justify new construction.

As the market cap rate increases, the expected sale price declines, as does the gross profit 
$$\text{Gross sales price } – \text{Total development costs}$$ 

If the market cap rate exceeds the development costs, a sale would result in a loss.

\newpage

### Commercial Real Estate Valuation

Real estate valuation is used as a general term describing the process of estimating the worth of a property from various perspectives, whereas a real estate appraisal is viewed as a formal opinion of a value provided by an appraiser, used in financial reports and in investment decision-making. 

For institutional investors, appraisals are performed once a year on real estate properties and are used in performance reporting.

The valuation methodologies for private market real estate are based on a number of assumptions.
 
The asset is valued if the following assumptions are true:

  i) A transaction occurred between a willing buyer and a willing seller.
  
  ii) The buyer and seller are well informed and acting in their own best interests.
  
  iii) The property has been in the market for a sufficient time for the buyers to have had ample time to inspect the property.
  
  iv) The transaction is financed with cash or with traditional commercial real estate (CRE) financing.
  
The property being valued is the subject property.

The formal appraisal report for subject property will contain the following information:

  i) A legal description and a physical description of the property
  
  ii) The assets that are being valued
  
  iii) The purpose of the appraisal
  
  iv) The effective date of appraisal and value estimate
  
  v) The market data used, and the analysis of that data
  
  vi) Valuation techniques used by the appraiser

- Three Reasons for the Emphasis on Commercial Real Estate Equity

1) Most commercial real estate throughout the world is privately held rather than publicly traded.

2) Most of equity of residential real estate is held by occupier of property rather than by an institutional investor.

3) The valuation of equity claims to private commercial real estate drives the pricing of the credit risk in the valuation of commercial mortgages. 

- The Three Valuation Methodologies for Private Real Estate

1) Comparable sale prices approach

2) Cost approach

3) Income approach (capitalization rate, discounted cash flow, and gross income multiplier)

- The Comparable Sale Prices Approach

For non-income-producing properties, a discounted cash flow approach is not viable. 

When there are sufficient transactional data available, valuations are based on the comparable sale prices approach.

The comparable sale prices approach involves the use of data from recently sold properties. 

This is a subjective process whereby the subject property is compared to recently sold properties to get an estimate of value. 

The value of the subject property is then adjusted to reflect differences between it and the comparison properties.

In this approach, the real estate appraiser looks at sales of similar properties in the same geographic region as the property being appraised.

These actual sale prices give the appraiser an estimate of the transaction price per square foot of similar real estate properties.

The appraiser then adjusts these prices for the unique characteristics of the property being appraised.

The comparable sale prices approach has the advantage of being based on actual sales transactions. 

It tends to contain substantial subjectivity in the valuation of most property characteristics.

The comparable sale prices approach is also dependent on having sufficient sales data to make a reasonable estimate of a property’s market value.

The accuracy of the approach is lower when there is a lack of frequency of property sales.

Every property is unique, so it is difficult to adjust a square-foot calculation value from one property to form the value of another property accurately.

- The Cost Approach














































